// Huy's Dimensions
export const canvas_height = 600; // becoming depreciated
export const canvas_width = 940; // becoming depreciated
// Jack's Dimensions
// export const canvas_height = 750; // becoming depreciated
// export const canvas_width = 1600; // becoming depreciated

/**
 * Mapping layers via constants
 * These should always be used to reference layers when used as parameters to a function or when interacting with this.state.
 * This allows us to easily add and remove layers.
 */
export const base = 0;              // ctx0 // scene[base]
export const heat = 1;              // ctx1 // scene[heat]
export const gas = 2;               // ctx2 // scene[gas]
export const plasma = 3;            // ctx3 // scene[plasma]
export const keeper = 4;            // ctx4 // scene[keeper]
export const eject = 5;             // ctx5 // scene[eject]
export const hallThrusterOff = 6;   // ctx6 // scene[hallThrusterOff]
export const hallThrusterOn = 7;    // ctx7 // scene[hallThrusterOn]

export const heatTitleText = "Heat Inserts"
export const heatText = " Heaters are coiled around the cathode tube and are responsible for heating up the cathode insert to extreme temperatures, at least at 1200 degrees Celsius (or 2192 degrees Fahrenheit). Heaters are surrounded by a heat shield to trap heat in and protect other electrical components from the extreme heat generated by the heat inserts. The insert is made of special material which can emit electrons at high temperatures. The insert is placed inside of the hollow cathode and pushed against the orifice.";

export const gasTitleText2 = "Gas Feed"
export const gasText = " The role of the gas feed is to inject Xenon gas into the cathode tube. Xenon is a neutral or noble gas, meaning it doesn’t react to electric or magnetic fields, but when Xenon atom collides and gain electrons, it becomes a negatively charged particle. This process is called ionization. Since Xenon becomes a negatively charged particle, it can be attracted by positive voltage or magnetic field.";

export const plasmaTitleText = "Internal Plasma"
export const plasmaText = " When ionized Xenon is heated at super high temperatures, it changes to another physical matter, known as plasma.";

export const keeperTitleText = "Keeper Electrodes"
export const keeperText = " Keeper electrode is a conductive material having a positive voltage and will be used to create an electric field, a force field created around a charged material. This electric field is created by the positive voltage, so it attracts negatively charged particles but pushes positively charged particles. Therefore, the role of the keeper electrode is to pull the internal plasma out of the cathode tube.";

export const ejectTitleText = "Eject Plasma"
export const ejectText = " When the negatively charged plasma is pulled out of the cathode tube, we call the plasma as external plasma. The purpose of the external plasma is to pull positively charged plasma generated by the Hall thruster as well as is used to neutralize the spacecraft to prevent it from being charged.";

export const heatKeeperErrorTitleText = "Heat Keeper Error"
export const heatKeeperErrorText = " Heat Keeper Error Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum";
export const gasKeeperErrorText = " Gas Keeper Error Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum";
export const hallThusterOffText = "                        The hollow cathode is a component of the Hall thruster. Its key role is to emit electronic\n" +
    "                        plasma to pull the positive plasma inside the cabin of the Hall thruster, known as the internal\n" +
    "                        plasma. Another role of the hollow cathode, which is not least significant, is to neutralize the\n" +
    "                        rocket. Without the hollow cathode, when Hall thruster emits plasma, the Hall thruster is\n" +
    "                        negatively charging the entire rocket. This phenomenon can cause spacecraft erosion and reduce\n" +
    "                        the thrust force."