// Huy's Dimensions
export const canvas_height = 600; // becoming depreciated
export const canvas_width = 940; // becoming depreciated
// Jack's Dimensions
// export const canvas_height = 750; // becoming depreciated
// export const canvas_width = 1600; // becoming depreciated

/**
 * Mapping layers via constants
 * These should always be used to reference layers when used as parameters to a function or when interacting with this.state.
 * This allows us to easily add and remove layers.
 */
export const base = 0;              // ctx0 // scene[base]
export const heat = 1;              // ctx1 // scene[heat]
export const gas = 2;               // ctx2 // scene[gas]
export const plasma = 3;            // ctx3 // scene[plasma]
export const keeper = 4;            // ctx4 // scene[keeper]
export const eject = 5;             // ctx5 // scene[eject]
export const hallThrusterOff = 6;   // ctx6 // scene[hallThrusterOff]
export const hallThrusterOn = 7;    // ctx7 // scene[hallThrusterOn]

export const hallThrusterPrimaryText = "The large circular component to the left is a Hall thruster, there are multiple of these on the spacecraft and they’re responsible for propelling the spacecraft through outer space. The Hall thruster produces thrust by ionizing atoms and shooting them away from the spacecraft at incredibly high speeds. You can use the power button below to turn the thruster on and see it in action. "

export const hallThrusterSecondaryOnText = "The Hall thruster has a source of particles it uses as propellant, while being stored the particles are neutral, meaning they don't react with electromagnetic electric fields (like magnets), making them easy to store. When it needs to use them, it ionizes them, making them react to electromagnetic fields. The hall thruster generates an extremely strong magnetic field which propels the particles from inside the thruster out and away from the spacecraft at extremely high speeds. This interaction is like trying to stick the wrong ends of two strong magnets together. "
export const hallThrusterSecondaryOffText = "We can't just simply ionize a particle, to ionize a particle we need electrons or other ionized particles, for this we need the hollow cathode."

export const cathodeShellPrimaryTitleText = "The Hollow Cathode"
export const cathodeShellPrimaryText = "This is a hollow cathode; it has two main jobs when it comes to propelling the Psyche spacecraft. Its first job is to supply the Hall thruster with a stream of electrons and ions which it can use to ionize particles. The hollow cathode emits electrons and ionized xenon particles which can ionize or neutralize other particles. The other job of the hollow cathode is to neutralize the ions as they fly away from the spacecraft. Ionized particles react to electromagnetic fields and if let loose in space may end up sticking to other parts of the spacecraft or interfering with its sensors, so the hollow cathode needs to return the ionized particles back to normal by supplying extra electrons and ions to balance them out. Click on the cathode again or press the next button below to explore how the hollow cathode produces these electrons."

export const heatTitleText = "Heat Inserts"
export const heatText = " Heaters are coiled around the cathode tube and are responsible for heating up the cathode insert to extreme temperatures, at least at 1200 degrees Celsius (or 2192 degrees Fahrenheit). Heaters are surrounded by a heat shield to trap heat in and protect other electrical components from the extreme heat generated by the heat inserts. The insert is made of special material which can emit electrons at high temperatures. The insert is placed inside of the hollow cathode and pushed against the orifice.";

export const gasTitleText2 = "Gas Feed"
export const gasText = " The role of the gas feed is to inject Xenon gas into the cathode tube. Xenon is a neutral or noble gas, meaning it doesn’t react to electric or magnetic fields, but when Xenon atom collides and gain electrons, it becomes a negatively charged particle. This process is called ionization. Since Xenon becomes a negatively charged particle, it can be attracted by positive voltage or magnetic field.";

export const plasmaTitleText = "Internal Plasma"
export const plasmaText = " When ionized Xenon is heated at super high temperatures, it changes to another physical matter, known as plasma.";

export const keeperTitleText = "Keeper Electrodes"
export const keeperText = " Keeper electrode is a conductive material having a positive voltage and will be used to create an electric field, a force field created around a charged material. This electric field is created by the positive voltage, so it attracts negatively charged particles but pushes positively charged particles. Therefore, the role of the keeper electrode is to pull the internal plasma out of the cathode tube.";

export const ejectTitleText = "Eject Plasma"
export const ejectText = " When the negatively charged plasma is pulled out of the cathode tube, we call the plasma as external plasma. The purpose of the external plasma is to pull positively charged plasma generated by the Hall thruster as well as is used to neutralize the spacecraft to prevent it from being charged.";

export const heatKeeperErrorTitleText = "Heat Keeper Error"
export const heatKeeperErrorText = " Heat Keeper Error Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum";
export const gasKeeperErrorText = " Gas Keeper Error Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum";
